# Example configuration: defines gRPC/RPC endpoints and monitoring interval
#    - "8pQKHs1xmJ1ALt8LyrU5HPC8M7esSfwksqdVh3Eu7zWH" # Empty value means no filtering; replace with target account public keys if needed.
rpc: http://127.0.0.1:8899
grpc: 127.0.0.1:10000
interval: 5s
log_level: info

metrics:
  prometheus_port: 9464

filters:
  accounts:
    - "6avCzMrjUDebRYtSoQ6GPQENjoxDaD2Udik8JzRnKbtb" # Target account public key for local testbed monitoring.

reconnect:
  retries: -1 # -1 means reconnect indefinitely
  backoff: 2s
