apiVersion: v1
kind: Service
metadata:
  name: solana-geyser-grpc
  labels:
    app.kubernetes.io/name: solana-containerised-testbed
    app.kubernetes.io/component: geyser-grpc
    app.kubernetes.io/part-of: solana-containerised-testbed
    testbed.solana/stage: observability-core
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: solana-containerised-testbed
    app.kubernetes.io/component: validator
  ports:
    - name: geyser-grpc
      port: 10000
      targetPort: geyser-grpc
