apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solana-observability

resources:
  - namespace.yaml
  - validator-configmap.yaml
  - validator-geyser-configmap.yaml
  - validator-ledger-pvc.yaml
  - validator-headless-service.yaml
  - validator-statefulset.yaml
  - rpc-service.yaml
  - geyser-grpc-service.yaml
  - wallet-init-job.yaml
  - monitor-configmap.yaml
  - monitor-deployment.yaml
  - metrics-service.yaml
