apiVersion: v1
kind: Service
metadata:
  name: solana-metrics
  labels:
    app.kubernetes.io/name: solana-containerised-testbed
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: solana-containerised-testbed
    testbed.solana/stage: observability-core
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: solana-containerised-testbed
    app.kubernetes.io/component: monitor
  ports:
    - name: metrics
      port: 9464
      targetPort: metrics
