apiVersion: v1
kind: Namespace
metadata:
  name: solana-observability
  labels:
    app.kubernetes.io/name: solana-containerised-testbed
    app.kubernetes.io/component: observability-core
    app.kubernetes.io/part-of: solana-containerised-testbed
    testbed.solana/stage: observability-core
