[k8s_control_plane]
k8s-cp-01 ansible_host=192.168.122.101

[k8s_workers]
k8s-worker-01 ansible_host=192.168.122.102
k8s-worker-02 ansible_host=192.168.122.103

[k8s:children]
k8s_control_plane
k8s_workers

[k8s:vars]
ansible_user=khoshaba
ansible_python_interpreter=/usr/bin/python3
